优化代码和容错处理
sugarforever/chat-ollama pull request #41
Opened 2024-03-12 02:02 UTC by satrong

- 处理 username password 为 null 情况
- 上传知识库增加判断 名称 是否已存在
- 修复指令返回 null 导致报错

2024-03-13 15:27 UTC, sugarforever requested changes

2024-03-14 00:30 UTC, satrong commented on pages/knowledgebases/index.vue
> +  <ClientOnly>
因为浏览器端发出了警告

![图片](https://github.com/sugarforever/chat-ollama/assets/5283258/4a1fc134-8888-446a-8a1e-b602493663ae)

2024-03-14 00:56 UTC, satrong commented on server/api/knowledgebases/index.post.ts
> +    }
加了下面的代码
```js
event.node.res.statusCode = 409;
```

2024-03-14 01:07 UTC, satrong commented
代码冲突的有点多，我重新发个pr

2024-03-14 01:07 UTC, closed without merging