Multiple docker images
sugarforever/chat-ollama pull request #454
Opened 2024-05-15 08:43 UTC by gallexy

修改docker compose yaml文件，推送两个平台镜像
修改.dockerignorefile，增加node_modules,避免本地执行docker build报错
docker-compose.yaml文件，增加
    extra_hosts:
      - "host.docker.internal:host-gateway"
避免在linux上运行容器找不到ollama服务

2024-05-16 00:02 UTC, sugarforever requested changes

2024-05-16 00:02 UTC, sugarforever commented on .github/workflows/docker-image.yaml
> +        tags: gallexy/chatollama:latest
这里标签还是换成0001coder吧。

2024-05-16 00:02 UTC, sugarforever commented on .github/workflows/docker-image.yaml
> +        platforms: linux/amd64,linux/arm64
这里可以把 linux/arm64/v8 也加上

2024-05-17 01:02 UTC, gallexy commented on docker-compose_arm.yaml
> +  busybox:
busybox是测试时用的，现在删除了

2024-05-17 01:02 UTC, gallexy commented on .github/workflows/docker-image.yaml
> +        tags: gallexy/chatollama:latest
换成0001coder我没有权限推送，现在设成根据项目名称打标签。

2024-05-17 01:02 UTC, gallexy commented on .github/workflows/docker-image.yaml
> +        platforms: linux/amd64,linux/arm64
加上了，试了一下有没有v8效果都是一样的，arm架构会build一个版本的镜像

2024-05-17 10:01 UTC, sugarforever approved these changes

2024-05-17 10:01 UTC, sugarforever commented on .github/workflows/docker-image.yaml
> +        tags: gallexy/chatollama:latest
👌

2024-05-17 10:01 UTC, merged

2024-05-17 10:29 UTC, sugarforever commented
> 修改docker compose yaml文件，推送两个平台镜像 修改.dockerignorefile，增加node_modules,避免本地执行docker build报错 docker-compose.yaml文件，增加 extra_hosts: - "host.docker.internal:host-gateway" 避免在linux上运行容器找不到ollama服务

我调整了一下workflow，这样能保证发布的镜像和以前一致，避免老用户没法更新镜像。

https://hub.docker.com/repository/docker/0001coder/chatollama/tags

你看看这些镜像你是否能正常运行